### ISSUE TITLE
Release VS 2022 support

### ISSUE THREAD

**Issue by Roshinator** [alexcrichton/cmake-rs#135]
This package is very important to the community, but despite having visual studio support added in, it has not been published to crates.io. This causes things to break in packages that use it unless we find the old visual studio 2019 download.

**Comment by rursprung** [comment]
@alexcrichton any chance that you could create this release with the code as-is? based on [crates.io](https://crates.io/crates/cmake) only you can create the release (only listed owner), so this isn't something anybody can contribute (the actual VS2022 compatibility is in the - unreleased - code since #134 has been merged two months ago).

i (and probably many others) would like to avoid having to either install an old version of VS or having to tamper with the dependencies of other libraries/programs just to get them to use the latest version of cmake-rs from git instead of a released version.

thanks!

**Comment by alexcrichton** [comment]
Sure, sorry for the delay, it's published now.
