### ISSUE TITLE
Should be "MinGW Makefile"?

### ISSUE THREAD

**Issue by FredrikNoren** [alexcrichton/cmake-rs#3]
From https://cmake.org/cmake/help/v3.4/generator/MSYS%20Makefiles.html it sounds like it shouldnt be "MSYS Makefile" but rather "MinGW Makefile" when the target is windows. (Getting errors with this currently on Windows)

**Comment by alexcrichton** [comment]
MinGW Makefile is actually subtly different I think where it calls `mingw32-make` instead of normal `make`, so I think that MSYS is more appropriate, but did it end up causing problems for you?

**Comment by FredrikNoren** [comment]
@alexcrichton Well, I was trying to build a library and only got it working with MinGW makefiles, but after having looked around it seems like a lot of rust-sys libraries are using MSYS so I think it might actually be  a better way forward for me to try to make this work with MSYS instead. Closing for now

**Comment by dylanede** [comment]
@alexcrichton I believe that in practice there is pretty much no usage difference between `mingw32-make` and `make` other than the name, yet this is enough to cause a problem for CMake if "MSYS Makefiles" is provided instead of "MinGW Makefiles" and only `mingw32-make` is available. Since both should work, would it make sense to test whether `make` or `mingw32-make` are on `PATH` and select `MSYS Makefiles` or `MinGW Makefiles" as appropriate, defaulting to "MSYS Makefiles" if both are available? I can make a PR for this.

**Comment by alexcrichton** [comment]
@dylanede sure! I'd be fine with either approach of:

* If `MSYS Makefiles` is the generate but `make.exe` isn't available, also check for `mingw32-make` and if *that's* available then use `MinGW Makefiles`
* Add a `generator` option to the configuration which allows configuring the generator used.
