### ISSUE TITLE
Determine default value of static_crt using RFC 1721

### ISSUE THREAD

**Issue by jethrogb** [alexcrichton/cmake-rs#34]
https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md

**Comment by alexcrichton** [comment]
Do you have some more information for this bug? Build logs? An example? etc

**Comment by jethrogb** [comment]
More of a feature request and not a bug. I don't really have any additional information. I was reading through the 1.19 release notes about RFC 1721 and remembered there was something in cmake related to that. I think the setting could/should be automatic.

**Comment by alexcrichton** [comment]
Ok, in that case I believe this is already implemented, so closing

**Comment by jethrogb** [comment]
I don't think so: https://github.com/alexcrichton/cmake-rs/search?utf8=%E2%9C%93&q=CARGO_CFG_TARGET_FEATURE&type=

**Comment by alexcrichton** [comment]
If you've got a concrete bug report, that'd be much appreciated!

**Comment by jethrogb** [comment]
I thought I was pretty clear: The default value of static_crt should be automatically determined

**Comment by alexcrichton** [comment]
Please take the time to test this out and report a bug if you think there's a bug. I implemented support for crt-static in this crate a very long time ago and it's been working ever since then in a large number of projects this is used for. The support for selection of defaults comes from the `gcc` crate, not this crate.
